// <auto-generated />
using System;
using DataReplayer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataReplayer.Migrations
{
    [DbContext(typeof(ReplayerDbContext))]
    [Migration("20260416061539_AddRecordedRtlsEvents")]
    partial class AddRecordedRtlsEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataReplayer.Domain.Entities.RecordedDataEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("TrackerId");

                    b.ToTable("RecordedEvents", (string)null);
                });

            modelBuilder.Entity("DataReplayer.Domain.Entities.RecordedRtlsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UwbMacAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("UwbMacAddress");

                    b.ToTable("RecordedRtlsEvents");
                });

            modelBuilder.Entity("DataReplayer.Domain.Entities.ReplayerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRecordingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRtlsRecordingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MqttBrokerHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MqttBrokerPort")
                        .HasColumnType("integer");

                    b.Property<string>("MqttPassword")
                        .HasColumnType("text");

                    b.Property<string>("MqttUsername")
                        .HasColumnType("text");

                    b.Property<int>("RetentionHours")
                        .HasColumnType("integer");

                    b.Property<string>("RtlsWebSocketUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscribedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackerIdTopicSegmentIndex")
                        .HasColumnType("integer");

                    b.Property<string>("TrackersWhiteList")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
